### ISSUE TITLE
Unexpected error: Cannot read properties of undefined (reading "url")

### ISSUE THREAD

**Issue by Nxtivision** [sundevista/youtube-template#1]
Hello!

I just tried your plugin, however, found an unexpected error while pasting the url. So, I tested your URL presented in the README, and only 3 works correctly:

- https://youtube.com/shorts/0dPkkQeRwTI?feature=share
- https://youtube.com/shorts/0dPkkQeRwTI
- http://www.youtube.com/user/IngridMichaelsonVEVO#p/a/u/1/QdK8U-VIH_o

All the other URLs fail to import.
Did I do something wrong ? 
Set correctly the Google Cloud API, activated the Youtube Data API also 🤔 

Thank you in advance !

**Comment by sundevista** [comment]
Hello! I have tried to use these links, and they work like a charm (attaching a screenshot of one of them). Please check if you have set the proper API key. You can open the developer tools inside of Obsidian, and it should throw an error to the console if something is wrong.

<img width="1495" alt="Screenshot 2024-01-28 at 18 48 57" src="https://github.com/sundevista/youtube-template/assets/56955307/3778819a-652b-45db-bcc8-1287e6b56b1d">

**Comment by sundevista** [comment]
Hello, @Nxtivision! I've tried to use these links and some from my YouTube feed. And if you say these three work, it means that your API key is set correctly. Can you send me a sample of URLs that don't work?

**Comment by Nxtivision** [comment]
🔴 Here are some links where it does not work:

https://youtu.be/W7m6pmNCxVs
https://youtu.be/I3RM_Pr2LZs
https://youtu.be/x0021G3uU7A


🟢 And here are links where **it works**:

https://youtu.be/zXFcOWoHRko
https://youtu.be/qteX-0AE_5U
https://youtu.be/mqwM0w71GEo

Quite weird...

**Comment by sundevista** [comment]
@Nxtivision, I can reproduce the issue. It will be fixed as soon as possible.

**Comment by sundevista** [comment]
Hello, @Nxtivision! The issue has been resolved with the 1.0.9 release. Please update the plugin and let me know if it works as needed.

The issue occurred because of the "maxres" field that was used to download thumbnails. The videos you sent (the ones that weren't working) didn't have a "maxres" thumbnail, so the plugin reported the absence of "maxres.url". Now the plugin searches for the best quality thumbnail, so it will work with any video, even if its thumbnail is a 1x1 pixel black square.

Thanks for catching that!

**Comment by Nxtivision** [comment]
And I can confirm you that it works as expected !

Thank you for your time ;)
