### ISSUE TITLE
Error If Folder Already Exists

### ISSUE THREAD

**Issue by VentureTactics** [sundevista/youtube-template#19]
When using the path template, it seems to error when the channel folder already exists:
![image](https://github.com/sundevista/youtube-template/assets/88736327/5acef078-6330-4381-a628-a592cad5b7ef)

It created it perfectly well for the first video.
The second video (which is in the same youtube channel as the first) gave the above error when trying to import.

**Comment by oscaromsn** [comment]
same here

**Comment by kud3n013** [comment]
Same here. I tried toggle off the option and it worked .. for a day or two. Then the problem reoccur today and can't be reverse anymore.

**Comment by sundevista** [comment]
The potential fix was released with 1.1.6 update. Please, update to the latest version and check if issue resolved on your side.

Thanks for your patience.

**Comment by sundevista** [comment]
I'll close the issue for now, feel free to reopen it if you encounter this error with the latest version

**Comment by janegilring** [comment]
I get the same error.
It seems like it is related to the attachments directory.

My setup:
- Folder to save notes: youtube
- Create folders: true

After trying to insert a YouTube template, it works once.
Next time, it returns the "Folder Already Exist" error.

I then noticed it has created an attachments directory on the root of the vault.
If I rename this to e.g. attachments2, inserting a YouTube template works once again.

I suppose this is an issue with the detection logic for the attachments folder.

Also, would it be possible to place this folder in the directory specified under "Folder to save notes" rather than the root of the vault?

**Comment by sundevista** [comment]
This issue is now tracked in #21
